### ISSUE TITLE
Create a unix-friendly bin

### ISSUE THREAD

**Issue by bloodyowl** [iLambda/lsdj-wave-cruncher#1]
The API should be installable using npm and runnable as a command line :

``` console
$ lsdjcrunch crunch ...options
$ lsdjcrunch patch ...options
$ lsdjcrunch crunch-patch ...options
$ lsdjcrunch export ...options
```

Also, commands should have a `--output` or `-o` option for the output file. If not provided, the output file should be piped to stdout

``` javascript
const output = (file: Stream, options) {
  file
    .pipe(options.output ? fs.createWriteStream(options.output) : process.stdout)
}
```

**Comment by iLambda** [comment]
I'll look into this for the next release.
