### ISSUE TITLE
Auto-detect wav frequency

### ISSUE THREAD

**Issue by urbster1** [iLambda/lsdj-wave-cruncher#2]
I just tested this and it seems doable to add a method to auto-detect the frequency of a wav file. This was the code I used and it requires fs, node-wav, and pitchfinder

```
const fs = require("fs");
const wav = require("node-wav");
const Pitchfinder = require("pitchfinder");
 
// see below for optional constructor parameters. 
const detectPitch = new Pitchfinder.YIN();
 
const buffer = fs.readFileSync("PATH_TO_WAV");
const decoded = wav.decode(buffer); // get audio data from file using `wav-decoder` 
const float32Array = decoded.channelData[0]; // get a single channel of sound 
const pitch = detectPitch(float32Array); // null if pitch cannot be identified
console.log("Frequency detected: " + parseFloat(pitch) + " Hz")
```

**Comment by urbster1** [comment]
I've added the code I've implemented to a fork of this project.

By the way, can I just say that this is a total game-changer for LSDJ! Thanks so much for putting it together!

**Comment by iLambda** [comment]
It's a really neat idea. I think it'd be awesome to add a flag to the command so one can force specify a frequency ! I'll look into this soon.

**Comment by urbster1** [comment]
I submitted a couple pull requests to add this feature - you can specify note value, frequency, or "auto" to try auto-detection. Tested it and it works really well!!
